name: Generate RULE-SET
on:
  workflow_dispatch:
  schedule:
    - cron: "30 22 * * *"
  push:
    branches:
      - master
    paths-ignore:
      - "**/README.md"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set variables
        run: |
          echo "update_version=$(date -d '+8 hours' +%Y-%m-%d)" >> ${GITHUB_ENV}
        shell: bash
      
      - name: Download mihomo domain ruleset
        run: |
          mkdir -p clash/domains
          files=(
              'fake_ip_filter.list https://raw.githubusercontent.com/juewuy/ShellCrash/refs/heads/dev/public/fake_ip_filter.list'
              'adrules.list https://raw.githubusercontent.com/Cats-Team/AdRules/main/adrules_domainset.txt'
              'httpdns.list https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/category-httpdns-cn.list'
              'apple-cn.list https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/apple@cn.list'
              'microsoft-cn.list https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/microsoft@cn.list'
              'download.list https://ruleset.skk.moe/Clash/domainset/download.txt'
              'cdn.list https://ruleset.skk.moe/Clash/domainset/cdn.txt'
              'apple.list https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo-lite/geosite/apple.list'
              'games.list https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/category-games.list'
              'tiktok.list https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/tiktok.list'
              'bilibili.list https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo-lite/geosite/bilibili.list'
              'onedrive.list https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/onedrive.list'
              'microsoft.list https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/microsoft.list'
              'youtube.list https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/youtube.list'
              'google.list https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/google.list'
              'spotify.list https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/spotify.list'
              'twitch.list https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/twitch.list'
              'bahamut.list https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/bahamut.list'
              'disney.list https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/disney.list'
              'hbo.list https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/hbo.list'
              'primevideo.list https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/primevideo.list'
              'netflix.list https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/netflix.list'
              'tld-proxy.list https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/tld-!cn.list'
              'proxy.list https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/geolocation-!cn.list'
              'cn.list https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/cn.list'
          )
          for file in "${files[@]}"; do
              set -- $file
              echo "Downloading: $2"
              curl -A "Surge iOS/3367" -sSL -o "clash/domains/$1" "$2" || { echo "Download Failed: $2"; exit 1; }
              sed -i -e '/this_ruleset_is_made_by_sukkaw.ruleset.skk.moe/d' "clash/domains/$1"
          done
          echo "Files downloaded successfully."
          
      - name: Generate apns.list file
        run: |
          curl -sSL 'https://github.com/QuixoticHeart/rule-set/raw/refs/heads/master/custom/apns.list' | grep -E 'DOMAIN,|DOMAIN-SUFFIX,' | sed -e 's/^DOMAIN,//' -e 's/^DOMAIN-SUFFIX,/+\./' > "clash/domains/apns.list"
          
      - name: Generate appleproxy.list file
        run: |
          curl -sSL 'https://github.com/blackmatrix7/ios_rule_script/raw/refs/heads/master/rule/Clash/AppleProxy/AppleProxy.list' | grep -E 'DOMAIN,|DOMAIN-SUFFIX,' | sed -e 's/^DOMAIN,//' -e 's/^DOMAIN-SUFFIX,/+\./' > "clash/domains/appleproxy.list"

      - name: Generate games-cn.list file
        run: |
          urls=(
              'https://github.com/blackmatrix7/ios_rule_script/raw/refs/heads/master/rule/Clash/SteamCN/SteamCN.list' 
              'https://github.com/blackmatrix7/ios_rule_script/raw/refs/heads/master/rule/Clash/Game/GameDownloadCN/GameDownloadCN.list' 
              'https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/category-games@cn.list' 
          )
          > "clash/domains/games-cn.list"
          # 使用 curl 下载并合并
          for i in 0 1; do
              curl -sSL "${urls[$i]}" | grep -E 'DOMAIN,|DOMAIN-SUFFIX,' | sed -e 's/^DOMAIN,//' -e 's/^DOMAIN-SUFFIX,/+\./' >> "clash/domains/games-cn.list" || { echo "Download Failed: "${urls[$i]}" "; exit 1; }
              echo "" >> "clash/domains/games-cn.list"
          done
            
          curl -sSL "${urls[2]}" >> "clash/domains/games-cn.list" || { echo "Download Failed: "${urls[2]}" "; exit 1; }

      - name: Generate gits.list file
        run: |
          urls=(
              'https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/github.list' 
              'https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/gitlab.list' 
              'https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/gitee.list' 
              'https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/gitbook.list' 
          )
          > "clash/domains/gits.list"
          # 使用 curl 下载并合并
          for i in 0 1 2 3; do
              curl -sSL "${urls[$i]}" >> "clash/domains/gits.list" || { echo "Download Failed: "${urls[$i]}" "; exit 1; }
              echo "" >> "clash/domains/gits.list"
          done

      - name: Generate ai.list file
        run: |
          urls=(
              'https://github.com/blackmatrix7/ios_rule_script/raw/refs/heads/master/rule/Clash/OpenAI/OpenAI.list' 
              'https://github.com/blackmatrix7/ios_rule_script/raw/refs/heads/master/rule/Clash/Gemini/Gemini.list' 
              'https://github.com/blackmatrix7/ios_rule_script/raw/refs/heads/master/rule/Clash/Copilot/Copilot.list' 
              'https://github.com/blackmatrix7/ios_rule_script/raw/refs/heads/master/rule/Clash/Claude/Claude.list' 
              'https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/category-ai-chat-!cn.list' 
          )
          > "clash/domains/ai.list"
          # 使用 curl 下载并合并
          for i in 0 1 2 3; do
              curl -sSL "${urls[$i]}" | grep -E 'DOMAIN,|DOMAIN-SUFFIX,' | sed -e 's/^DOMAIN,//' -e 's/^DOMAIN-SUFFIX,/+\./' >> "clash/domains/ai.list" || { echo "Download Failed: "${urls[$i]}" "; exit 1; }
              echo "" >> "clash/domains/ai.list"
          done
          curl -sSL "${urls[4]}" >> "clash/domains/ai.list" || { echo "Download Failed: "${urls[4]}" "; exit 1; }

      - name: Generate crypto.list file
        run: |
          urls=(
              'https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/category-cryptocurrency.list' 
              'https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/category-finance.list' 
          )
          > "clash/domains/crypto.list"
          # 使用 curl 下载并合并
          for i in 0 1; do
              curl -sSL "${urls[$i]}" >> "clash/domains/crypto.list" || { echo "Download Failed: "${urls[$i]}" "; exit 1; }
              echo "" >> "clash/domains/crypto.list"
          done

      - name: Generate socialmedia.list file
        run: |
          urls=(
              'https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/reddit.list' 
              'https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/discord.list' 
              'https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/whatsapp.list' 
              'https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/line.list'
              'https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/instagram.list'
              'https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/telegram.list'
              'https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/telegram.list'
              'https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/twitter.list'
          )
          > "clash/domains/socialmedia.list"
          # 使用 curl 下载并合并
          for i in 0 1 2 3 4 5 6 7; do
              curl -sSL "${urls[$i]}" >> "clash/domains/socialmedia.list" || { echo "Download Failed: "${urls[$i]}" "; exit 1; }
              echo "" >> "clash/domains/socialmedia.list"
          done
          
      - name: Generate private.list file
        run: |
          urls=(
          'https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/private.list' 
          'https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/tracker.list' 
          'https://github.com/XIU2/TrackersListCollection/raw/refs/heads/master/all.txt'
          )
          > "clash/domains/private.list"

          for i in 0 1; do
              curl -sSL "${urls[$i]}" >> "clash/domains/private.list" || { echo "Download Failed: "${urls[$i]}" "; exit 1; }
              echo "" >> "clash/domains/private.list"
          done
            
          curl -sSL "${urls[2]}" | grep -oP '([a-zA-Z0-9-]+\.)+[a-zA-Z]{2,6}' >> "clash/domains/private.list" || { echo "Download Failed: "${urls[2]}" "; exit 1; } 
          
      - name: Generate custom_cn.list file
        run: |  
          grep -v -x -f clash/domains/bilibili.list clash/domains/cn.list > clash/domains/custom_cn.list

      - name: Download mihomo ipcidr ruleset
        run: |
          mkdir -p clash/ipcidr
          files=(
              'applecidr.list https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo-lite/geoip/apple.list'
              'bilibilicidr.list https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo-lite/geoip/bilibili.list'
              'googlecidr.list https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geoip/google.list'
              'netflixcidr.list https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geoip/netflix.list'
              'cncidr.list https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geoip/cn.list'
          )
          for file in "${files[@]}"; do
              set -- $file
              echo "Downloading: $2"
              curl -A "Surge iOS/3367" -sSL -o "clash/ipcidr/$1" "$2" || { echo "Download Failed: $2"; exit 1; }
          done
          echo "Files downloaded successfully."

      - name: Generate apnscidr.list file
        run: |  
          curl -sSL 'https://github.com/QuixoticHeart/rule-set/raw/refs/heads/master/custom/apns.list' | grep 'IP-CIDR' | sed -e 's/^IP-CIDR,//' -e 's/^IP-CIDR6,//' -e 's/,no-resolve$//' > "clash/ipcidr/apnscidr.list"

      - name: Generate socialmediacidr.list file
        run: |
          urls=(
              'https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geoip/facebook.list' 
              'https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geoip/telegram.list' 
              'https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geoip/twitter.list' 
          )
          > "clash/ipcidr/socialmediacidr.list"
          # 使用 curl 下载并合并
          for i in 0 1 2; do
              curl -sSL "${urls[$i]}" >> "clash/ipcidr/socialmediacidr.list" || { echo "Download Failed: "${urls[$i]}" "; exit 1; }
              echo "" >> "clash/ipcidr/socialmediacidr.list"
          done

      - name: Generate privatecidr.list file
        run: |  
          curl -sSL 'https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geoip/private.list' > "clash/ipcidr/privatecidr.list"
          echo "" >> "clash/ipcidr/privatecidr.list"
          
          curl -sSL 'https://github.com/XIU2/TrackersListCollection/raw/refs/heads/master/all.txt' | grep -oP '\b(?:\d{1,3}\.){3}\d{1,3}\b' | sed 's/$/\/32/' >> "clash/ipcidr/privatecidr.list"
          echo "" >> "clash/ipcidr/privatecidr.list"    
          
          curl -sSL 'https://github.com/XIU2/TrackersListCollection/raw/refs/heads/master/all.txt' | grep -oP '\b([0-9a-fA-F]{1,4}:){7}[0-9a-fA-F]{1,4}\b|\b([0-9a-fA-F]{1,4}:){1,7}:|::[0-9a-fA-F]{1,4}(:[0-9a-fA-F]{1,4}){0,6}\b' | sed 's/$/\/128/' >> "clash/ipcidr/privatecidr.list"

      - name: Download mihomo classical ruleset
        run: |
          mkdir -p clash/classical
          files=(
              'iplocation-reject.list https://github.com/SunsetMkt/anti-ip-attribution/raw/refs/heads/main/generated/rule-set-reject.list'
              'iplocation-direct.list https://github.com/SunsetMkt/anti-ip-attribution/raw/refs/heads/main/generated/rule-set-direct.list'
              'iplocation-proxy.list https://github.com/SunsetMkt/anti-ip-attribution/raw/refs/heads/main/generated/rule-set-proxy.list'
              'download-classical.list https://ruleset.skk.moe/Clash/non_ip/download.txt'
              'cdn-classical.list https://ruleset.skk.moe/Clash/non_ip/cdn.txt'
          )
          for file in "${files[@]}"; do
              set -- $file
              echo "Downloading: $2"
              curl -A "Surge iOS/3367" -sSL -o "clash/classical/$1" "$2" || { echo "Download Failed: $2"; exit 1; }
              sed -i -e '/DOMAIN,this_ruleset_is_made_by_sukkaw.ruleset.skk.moe/d' "clash/classical/$1"
          done
          echo "Files downloaded successfully."        
      
      - name: Generate application.list file
        run: |
          curl -sSL 'https://github.com/Loyalsoldier/clash-rules/raw/refs/heads/release/applications.txt' | grep -v 'payload:' | sed -e 's/^[ \t]*- //' > "clash/classical/application.list"
          echo "" >> "clash/classical/application.list"
          
          curl -sSL 'https://github.com/blackmatrix7/ios_rule_script/raw/refs/heads/master/rule/Clash/Download/Download.list' >> "clash/classical/application.list"

      - name: Download and unzip `mihomo core`
        run: |
          mihomo_version=$(curl -sSL https://api.github.com/repos/MetaCubeX/mihomo/releases | grep 'tag_name' | grep -v 'Alpha' | head -n 1 | sed -e 's/.*v/v/' -e 's/".*//')
          wget "https://github.com/MetaCubeX/mihomo/releases/download/${mihomo_version}/mihomo-linux-amd64-${mihomo_version}.gz" -O - | gzip -d > ./mihomo
          chmod +x ./mihomo
           
      - name: Process raw ruleset files and generate mihomo mrs       
        run: |
          for file in clash/domains/*.list ; do
              awk '/^\s*[#;]/ { next } /^$/ { next } { sub(" //.*", ""); print }' "${file}" | sort -u -o "${file}"
              ./mihomo convert-ruleset domain text "${file}" "${file%.list}.mrs"
          done

          for file in clash/ipcidr/*.list ; do
              awk '/^\s*[#;]/ { next } /^$/ { next } { sub(" //.*", ""); print $0, ($1 ~ /:/ ? 1 : 0) }' "${file}" | sort -k2,2n -k1,1 | uniq | cut -d' ' -f1 > temp.list
              mv temp.list "${file}"
              ./mihomo convert-ruleset ipcidr text "${file}" "${file%.list}.mrs"
          done
          
          for file in clash/classical/*.list ; do
              awk '/^\s*[#;]/ { next } /^$/ { next } { sub(" //.*", ""); print }' "${file}" | sort -u -o "${file}"
          done

      - name: Release and upload assets
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          release_name: mihomo
          tag: mihomo
          overwrite: true
          body: |
            [mihomo](https://github.com/MetaCubeX/mihomo) rule-set 文件
            rule-set 文件更新于 ${{ env.update_version }}
          file_glob: true
          file: |
            ./clash/*

      - name: Git push assets to "mihomo" branch
        run: |
          cd clash || exit 1
          git init
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout -b mihomo
          git add .
          git commit -m "mihomo rule-set 规则集文件更新于 ${update_version}"
          git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
          git push -f origin mihomo

      - name: Purge jsdelivr CDN
        run: |
          cd clash || exit 1
          for file in $(ls); do
            curl -i "https://purge.jsdelivr.net/gh/${{ github.repository }}@mihomo/${file}"
          done
      
      - name: Delete old workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 3
          keep_minimum_runs: 1    
