name: Generate RULE-SET
on:
  workflow_dispatch:
  schedule:
    - cron: "30 22 * * *"
  push:
    branches:
      - master
    paths-ignore:
      - "**/README.md"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set variables
        run: |
          echo "update_version=$(date -d '+8 hours' +%Y-%m-%d)" >> ${GITHUB_ENV}
          echo "mihomo_domains=https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite" >> ${GITHUB_ENV}
          echo "mihomo_ipcidr=https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geoip" >> ${GITHUB_ENV}
          echo "bm7_surge=https://github.com/blackmatrix7/ios_rule_script/raw/refs/heads/master/rule/Surge" >> ${GITHUB_ENV}
        shell: bash
      
      - name: Generate directories
        run: |
          mkdir -p download/domains
          mkdir -p download/ipcidr
          mkdir -p download/surge
          mkdir -p download/classical
          mkdir -p download/other
          mkdir -p temp/domains
          mkdir -p temp/ipcidr
          mkdir -p temp/surge
          mkdir -p temp/classical
          mkdir -p clash/domains
          mkdir -p clash/ipcidr
          mkdir -p clash/classical
      
      - name: Download mihomo domain ruleset
        run: |          
          domain_lists=('category-httpdns-cn' 'apple@cn' 'apple' 'microsoft@cn' 'onedrive' 'microsoft' 'category-ai-chat-!cn' 'category-cryptocurrency' 'category-finance' 'category-games@cn' 'category-games' 'reddit' 'discord' 'whatsapp' 'line' 'instagram' 'facebook' 'telegram' 'twitter' 'tiktok' 'bilibili' 'youtube' 'google' 'spotify' 'twitch' 'bahamut' 'hbo' 'disney' 'primevideo' 'netflix' 'tld-!cn' 'tracker' 'gfw' 'geolocation-!cn' 'private' 'cn')
          
          for list in "${domain_lists[@]}"; do
              curl -sSL "${mihomo_domains}/${list}.list" | sed '$a\' > "download/domains/${list}.list"
          done

          files=(
              'fake_ip_filter.list https://raw.githubusercontent.com/juewuy/ShellCrash/refs/heads/dev/public/fake_ip_filter.list'
              'adrules.list https://raw.githubusercontent.com/Cats-Team/AdRules/main/adrules_domainset.txt'
              'cdn.list https://ruleset.skk.moe/Clash/domainset/cdn.txt'
              'download.list https://ruleset.skk.moe/Clash/domainset/download.txt' 
          )
          
          for file in "${files[@]}"; do
              set -- $file
              echo "Downloading: $2"
              curl -sSL "$2" | sed '$a\' > "download/domains/$1"
          done
          
          sed -i -e '/this_ruleset_is_made_by_sukkaw.ruleset.skk.moe/d' "download/domains/cdn.list"
          sed -i -e '/this_ruleset_is_made_by_sukkaw.ruleset.skk.moe/d' "download/domains/download.list"
               
      - name: Download mihomo ipcidr ruleset
        run: |
          ipcidr_lists=('facebook' 'telegram' 'twitter' 'google' 'netflix' 'private' 'cn')
                    
          for list in "${ipcidr_lists[@]}"; do
              curl -sSL "${mihomo_ipcidr}/${list}.list" | sed '$a\' > "download/ipcidr/${list}.list"
          done
      
      - name: Download surge ruleset
        run: |
          surge_lists=('AppleProxy' 'Download' 'OneDrive' 'Microsoft' 'GitHub' 'GitLab' 'Gitee' 'GitBook' 'OpenAI' 'Gemini' 'Copilot' 'Claude' 'SteamCN' 'Game' 'Reddit' 'Discord' 'Whatsapp' 'Line' 'Telegram' 'Instagram' 'Facebook' 'Twitter' 'TikTok' 'BiliBili' 'YouTube' 'Google' 'Spotify' 'Twitch' 'Bahamut' 'HBO' 'Disney' 'PrimeVideo' 'Netflix')
                              
          for list in "${surge_lists[@]}"; do
              curl -sSL "${bm7_surge}/${list}/${list}.list" | sed '$a\' > "download/surge/${list}.list"
          done

          files=(
              'GameDownloadCN.list https://github.com/blackmatrix7/ios_rule_script/raw/refs/heads/master/rule/Surge/Game/GameDownloadCN/GameDownloadCN.list'
              'Apple.list https://github.com/blackmatrix7/ios_rule_script/raw/refs/heads/master/rule/Surge/Apple/Apple_All.list'
              'Apns.list https://github.com/QuixoticHeart/rule-set/raw/refs/heads/master/custom/apns.list'
          )
          for file in "${files[@]}"; do
              set -- $file
              echo "Downloading: $2"
              curl -sSL "$2" | sed '$a\' > "download/surge/$1"
          done

      - name: Download classical ruleset
        run: |
          files=(
              'iplocation-reject.list https://github.com/SunsetMkt/anti-ip-attribution/raw/refs/heads/main/generated/rule-set-reject.list'
              'iplocation-direct.list https://github.com/SunsetMkt/anti-ip-attribution/raw/refs/heads/main/generated/rule-set-direct.list'
              'iplocation-proxy.list https://github.com/SunsetMkt/anti-ip-attribution/raw/refs/heads/main/generated/rule-set-proxy.list'
              'download-classical.list https://ruleset.skk.moe/Clash/non_ip/download.txt'
              'cdn-classical.list https://ruleset.skk.moe/Clash/non_ip/cdn.txt'
          )
          for file in "${files[@]}"; do
              set -- $file
              echo "Downloading: $2"
              curl -sSL "$2" | sed '$a\' > "download/classical/$1"
          done

          sed -i -e '/DOMAIN,this_ruleset_is_made_by_sukkaw.ruleset.skk.moe/d' "download/classical/cdn-classical.list"
          sed -i -e '/DOMAIN,this_ruleset_is_made_by_sukkaw.ruleset.skk.moe/d' "download/classical/download-classical.list"
      
      - name: Download other ruleset
        run: |
          files=(
              'trackers.list https://github.com/XIU2/TrackersListCollection/raw/refs/heads/master/all.txt'
              'applications.list https://github.com/Loyalsoldier/clash-rules/raw/refs/heads/release/applications.txt'
              'download-surge.list https://ruleset.skk.moe/List/non_ip/download.conf'
              'cdn-surge.list https://ruleset.skk.moe/List/non_ip/cdn.conf'
          )
          for file in "${files[@]}"; do
              set -- $file
              echo "Downloading: $2"
              curl -sSL "$2" | sed '$a\' > "download/other/$1"
          done
      
      - name: Copy final files
        run: |
          src_dir="download/domains"
          dst_dir="clash/domains"
          
          src_names=('category-httpdns-cn' 'fake_ip_filter' 'adrules' 'cdn' 'download' 'apple@cn' 'microsoft@cn' 'tld-!cn' 'gfw' 'geolocation-!cn' 'cn')
          dst_names=('httpdns' 'fake_ip_filter' 'adrules' 'cdn' 'download' 'apple-cn' 'microsoft-cn' 'tld-proxy' 'gfw' 'proxy' 'cn')

          for i in "${!dst_names[@]}"; do
              src_file="$src_dir/${src_names[i]}.list"
              dst_file="$dst_dir/${dst_names[i]}.list"
              cp "$src_file" "$dst_file"
          done
                
          cp download/ipcidr/cn.list clash/ipcidr/cncidr.list
          cp download/classical/*.list clash/classical/
      
      - name: Transform ruleset into clash domains
        run: |
          for file in download/surge/*.list ; do
              filename=$(basename "$file" .list)
              grep -E 'DOMAIN,|DOMAIN-SUFFIX,' "${file}" | sed -e 's/^DOMAIN,//' -e 's/^DOMAIN-SUFFIX,/+\./' > "temp/domains/${filename}.list"
          done
      
      - name: Transform ruleset into clash ipcidr
        run: |
          for file in download/surge/*.list ; do
              filename=$(basename "$file" .list)
              grep -E 'IP-CIDR[6]?,' "${file}" | sed -e 's/^IP-CIDR,//' -e 's/^IP-CIDR6,//' -e 's/,no-resolve$//' > "temp/ipcidr/${filename}.list"
          done
      
      - name: Generate final files
        run: |
          src1_dir="download/domains"
          src2_dir="temp/domains"
          dst_dir="clash/domains"

          src1_names=('apple' 'onedrive' 'microsoft' 'category-games' 'tiktok' 'bilibili' 'youtube' 'google' 'spotify' 'twitch' 'bahamut' 'hbo' 'disney' 'primevideo' 'netflix')

          src2_names=('Apple' 'OneDrive' 'Microsoft' 'Game' 'TikTok' 'BiliBili' 'YouTube' 'Google' 'Spotify' 'Twitch' 'Bahamut' 'HBO' 'Disney' 'PrimeVideo' 'Netflix')

          dst_names=('apple' 'onedrive' 'microsoft' 'games' 'tiktok' 'bilibili' 'youtube' 'google' 'spotify' 'twitch' 'bahamut' 'hbo' 'disney' 'primevideo' 'netflix')

          for i in "${!dst_names[@]}"; do
              src1_file="$src1_dir/${src1_names[i]}.list"
              src2_file="$src2_dir/${src2_names[i]}.list"
              dst_file="$dst_dir/${dst_names[i]}.list"

              cat "$src1_file" "$src2_file" > "$dst_file"
          done
           
      - name: Generate apns.list file
        run: |
          mv temp/domains/Apns.list clash/domains/apns.list
          mv temp/ipcidr/Apns.list clash/ipcidr/apnscidr.list
          
      - name: Generate appleproxy.list file
        run: |
          mv temp/domains/AppleProxy.list clash/domains/appleproxy.list
      
      - name: Generate applecidr.list file
        run: |
          mv temp/ipcidr/Apple.list clash/ipcidr/applecidr.list

      - name: Generate bilibilicidr.list file
        run: |
          mv temp/ipcidr/BiliBili.list clash/ipcidr/bilibilicidr.list
      
      - name: Generate netflixcidr.list file
        run: |
          cat 'download/ipcidr/netflix.list' \
              'temp/ipcidr/Netflix.list' \
          > clash/ipcidr/netflixcidr.list
          
      - name: Generate googlecidr.list file
        run: |  
          cat 'download/ipcidr/google.list' \
              'temp/ipcidr/Google.list' \
          > clash/ipcidr/googlecidr.list

      - name: Generate games-cn.list file
        run: |
          cat 'download/domains/category-games@cn.list' \
              'temp/domains/SteamCN.list' \
              'temp/domains/GameDownloadCN.list' \
          > clash/domains/games-cn.list

      - name: Generate gits.list file
        run: |
          cat 'temp/domains/GitHub.list' \
              'temp/domains/GitLab.list' \
              'temp/domains/Gitee.list' \
              'temp/domains/GitBook.list' \
          > clash/domains/gits.list
          
      - name: Generate ai.list file
        run: |
          cat 'temp/domains/OpenAI.list' \
              'temp/domains/Gemini.list' \
              'temp/domains/Copilot.list' \
              'temp/domains/Claude.list' \
              'download/domains/category-ai-chat-!cn.list' \
          > clash/domains/ai.list 

      - name: Generate crypto.list file
        run: |
          cat 'download/domains/category-cryptocurrency.list' \
              'download/domains/category-finance.list' \
          > clash/domains/crypto.list

      - name: Generate socialmedia.list file
        run: |
          cat 'temp/domains/Reddit.list' \
              'temp/domains/Discord.list' \
              'temp/domains/Whatsapp.list' \
              'temp/domains/Line.list' \
              'temp/domains/Instagram.list' \
              'temp/domains/Facebook.list' \
              'temp/domains/Telegram.list' \
              'temp/domains/Twitter.list' \
              'download/domains/reddit.list' \
              'download/domains/discord.list' \
              'download/domains/whatsapp.list' \
              'download/domains/line.list' \
              'download/domains/instagram.list' \
              'download/domains/facebook.list' \
              'download/domains/telegram.list' \
              'download/domains/twitter.list' \
          > clash/domains/socialmedia.list
          
          cat 'temp/ipcidr/Whatsapp.list' \
              'temp/ipcidr/Line.list' \
              'temp/ipcidr/Facebook.list' \
              'temp/ipcidr/Telegram.list' \
              'temp/ipcidr/Twitter.list' \
              'download/ipcidr/facebook.list' \
              'download/ipcidr/telegram.list' \
              'download/ipcidr/twitter.list' \
          > clash/ipcidr/socialmediacidr.list
                    
      - name: Generate private.list file
        run: |
          grep -oE '([a-zA-Z0-9-]+\.)+[a-zA-Z]{2,}' 'download/other/trackers.list' > 'temp/domains/Trackers.list' 
          
          cat <<EOF > ./temp/domains/Panels.list
          yacd.haishan.me
          yacd.metacubex.one
          d.metacubex.one
          metacubex.github.io
          metacubexd.pages.dev
          board.zash.run.place
          EOF
          
          cat 'temp/domains/Trackers.list' \
              'temp/domains/Panels.list' \
              'download/domains/tracker.list' \
              'download/domains/private.list' \
          > clash/domains/private.list

          grep -oE '([0-9]{1,3}\.){3}[0-9]{1,3}' 'download/other/trackers.list' | sed 's/$/\/32/' > "temp/ipcidr/TrackersV4.list"    
          
          grep -oE '([0-9a-fA-F]{1,4}:){7}[0-9a-fA-F]{1,4}|::([0-9a-fA-F]{1,4}:){0,6}[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,7}:|([0-9a-fA-F]{1,4}:){1,6}:[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,5}(:[0-9a-fA-F]{1,4}){1,2}|([0-9a-fA-F]{1,4}:){1,4}(:[0-9a-fA-F]{1,4}){1,3}|([0-9a-fA-F]{1,4}:){1,3}(:[0-9a-fA-F]{1,4}){1,4}|([0-9a-fA-F]{1,4}:){1,2}(:[0-9a-fA-F]{1,4}){1,5}|[0-9a-fA-F]{1,4}:((:[0-9a-fA-F]{1,4}){1,6})|:((:[0-9a-fA-F]{1,4}){1,7}|:)|fe80:(:[0-9a-fA-F]{0,4}){0,4}%[0-9a-zA-Z]{1,}|::1' 'download/other/trackers.list' | sed 's/$/\/128/' > "temp/ipcidr/TrackersV6.list"
          
          cat 'temp/ipcidr/TrackersV4.list' \
              'temp/ipcidr/TrackersV6.list' \
              'download/ipcidr/private.list' \
          > clash/ipcidr/privatecidr.list
                    
      - name: Generate custom_cn.list file
        run: |  
          grep -v -x -f clash/domains/bilibili.list clash/domains/cn.list > clash/domains/custom_cn.list
     
      - name: Generate application.list file
        run: |
          grep -v 'payload:' 'download/other/applications.list' | sed -e 's/^[ \t]*- //' > 'temp/classical/Application.list'

          sed -E '/^(DOMAIN-WILDCARD,|URL-REGEX,|USER-AGENT,)/d; s/DEST-PORT/DST-PORT/g' 'download/surge/Download.list' > 'temp/classical/Download.list'
          
          cat 'temp/classical/Application.list' \
              'temp/classical/Download.list' \
          > clash/classical/application.list

      - name: Download and unzip `mihomo core`
        run: |
          mihomo_version=$(curl -sSL https://api.github.com/repos/MetaCubeX/mihomo/releases | grep 'tag_name' | grep -v 'Alpha' | head -n 1 | sed -e 's/.*v/v/' -e 's/".*//')
          wget "https://github.com/MetaCubeX/mihomo/releases/download/${mihomo_version}/mihomo-linux-amd64-${mihomo_version}.gz" -O - | gzip -d > ./mihomo
          chmod +x ./mihomo
           
      - name: Process raw ruleset files and generate mihomo mrs       
        run: |
          for file in clash/domains/*.list ; do
              awk '/^\s*[#;]/ { next } /^$/ { next } { sub(" //.*", ""); print }' "${file}" | sort -uV -o "${file}"
              ./mihomo convert-ruleset domain text "${file}" "${file%.list}.mrs"
          done

          for file in clash/ipcidr/*.list ; do
              awk '/^\s*[#;]/ { next } /^$/ { next } { sub(" //.*", ""); print $0, ($1 ~ /:/ ? 1 : 0) }' "${file}" | sort -k2,2n -k1,1 | uniq | cut -d' ' -f1 > tmp.list && mv tmp.list "${file}"
              ./mihomo convert-ruleset ipcidr text "${file}" "${file%.list}.mrs"
          done
          
          for file in clash/classical/*.list ; do
              awk '
                  /^\s*[#;]/ { next }
                  /^$/ { next }
                  sub(" //.*", "");
                  /^DOMAIN,/         { print "0 " $0; next }
                  /^DOMAIN-SUFFIX,/  { print "1 " $0; next }
                  /^DOMAIN-KEYWORD,/ { print "2 " $0; next }
                  /^DOMAIN-REGEX,/   { print "3 " $0; next }
                  /^IP-CIDR,/        { print "4 " $0; next }
                  /^IP-CIDR6,/       { print "5 " $0; next }
                  /^IP-ASN,/         { print "6 " $0; next }
                  /^PROCESS-NAME,/   { print "7 " $0; next }
                  /^GEOSITE,/        { print "8 " $0; next }
                  /^GEOIP,/          { print "9 " $0; next }
                  /^AND,/            { print "10 " $0; next }
                  /^OR,/             { print "11 " $0; next }
                  /^NOT,/            { print "12 " $0; next }
                  /^SUB-RULE,/       { print "13 " $0; next }
                  /^DEST-PORT,/      { print "14 " $0; next }
                                     { print "15 " $0 }
              ' "${file}" | sort -k1,1n -k2,2 | uniq | cut -d' ' -f2- > tmp.list && mv tmp.list "${file}"
          done

      - name: Release and upload assets
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          release_name: mihomo
          tag: mihomo
          overwrite: true
          body: |
            [mihomo](https://github.com/MetaCubeX/mihomo) rule-set 文件
            rule-set 文件更新于 ${{ env.update_version }}
          file_glob: true
          file: |
            ./clash/*

      - name: Git push assets to "mihomo" branch
        run: |
          cd clash || exit 1
          git init
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout -b mihomo
          git add .
          git commit -m "mihomo rule-set 规则集文件更新于 ${update_version}"
          git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
          git push -f origin mihomo

      - name: Purge jsdelivr CDN
        run: |
          cd clash || exit 1
          for file in $(ls); do
            curl -i "https://purge.jsdelivr.net/gh/${{ github.repository }}@mihomo/${file}"
          done
      
      - name: Delete old workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 3
          keep_minimum_runs: 1    
